db:
  image: postgres:9.5.0
  ports:
    - "5432:5432"

# web:
#   build: .
#   command: bundle exec rails s -p 3000 -P tmp/pids/server.pid --binding 0.0.0.0
#   ports:
#     - "3000:3000"
#   links:
#     - db
